version: '3.7'

networks:
  default:
    name: brit-network
    external: true

services:
  api:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/brit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brit
      - POSTGRES_HOST=0.0.0.0
    volumes:
      - .:/app/
    ports:
      - 80:80
    depends_on:
      - db
    restart: always

  db:
    networks:
      - default
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=brit
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres
    restart: always

volumes:
  postgres:
